# Generated by Django 4.2 on 2026-07-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "پروفایل", "verbose_name_plural": "پروفایل ها"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "کاربر", "verbose_name_plural": "کاربر ها"},
        ),
    ]
