# Generated by Django 4.2 on 2026-07-18 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicemodel",
            options={
                "ordering": ["order"],
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمات",
            },
        ),
        migrations.AddField(
            model_name="servicemodel",
            name="about_service",
            field=models.TextField(blank=True, verbose_name="در مورد خدمات"),
        ),
        migrations.AddField(
            model_name="servicemodel",
            name="key_elements_description",
            field=models.TextField(blank=True, verbose_name="عناصر کلیدی"),
        ),
        migrations.AddField(
            model_name="servicemodel",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicemodel",
            name="spaces_description",
            field=models.TextField(blank=True, verbose_name="انواع فضاها"),
        ),
        migrations.AlterField(
            model_name="servicegallerymodel",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="services.servicemodel",
            ),
        ),
        migrations.DeleteModel(
            name="ServiceDetailModel",
        ),
    ]
