# Generated by Django 4.2 on 2026-07-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_servicemodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicemodel",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
