# Generated by Django 4.2 on 2026-07-01 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="images/")),
                ("description", models.TextField(blank=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_list",
                        to="projects.projectcategorymodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectDetailModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("image", models.ImageField(upload_to="projects/")),
                (
                    "client",
                    models.CharField(max_length=255, verbose_name="نام کارفرما"),
                ),
                (
                    "project_type",
                    models.CharField(max_length=255, verbose_name="نوع پروژه"),
                ),
                ("location", models.CharField(max_length=255, verbose_name="موقعیت")),
                ("year", models.PositiveIntegerField(verbose_name="سال")),
                ("short_description", models.TextField(verbose_name="توضیح کوتاه")),
                ("result_description", models.TextField(verbose_name="نتیجه پروژه")),
                ("total_area", models.PositiveIntegerField(verbose_name="متراژ کل")),
                ("rooms", models.PositiveIntegerField(verbose_name="تعداد اتاق")),
                (
                    "floor_area",
                    models.PositiveIntegerField(verbose_name="متراژ هر طبقه"),
                ),
                ("building_area", models.PositiveIntegerField(verbose_name="زیربنا")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="projects_details",
                        to="projects.projectcategorymodel",
                    ),
                ),
            ],
        ),
    ]
