# Generated by Django 4.2 on 2026-07-16 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmodel",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "پروژه",
                "verbose_name_plural": "پروژه\u200cها",
            },
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="building_area",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="زیربنا"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="client",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="نام کارفرما"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="extra_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects_extra",
                to="projects.projectcategorymodel",
                verbose_name="دسته\u200cبندی\u200cهای اضافه",
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="floor_area",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="متراژ هر طبقه"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="project_type",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="نوع پروژه"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="result_description",
            field=models.TextField(blank=True, verbose_name="نتیجه پروژه"),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="rooms",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="تعداد اتاق"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="توضیح کوتاه جزئیات"),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="total_area",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="متراژ کل"
            ),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects_list",
                to="projects.projectcategorymodel",
                verbose_name="دسته\u200cبندی اصلی",
            ),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیح کوتاه لیست"),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="تصویر شاخص"),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="location",
            field=models.CharField(max_length=255, verbose_name="موقعیت"),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="year",
            field=models.PositiveIntegerField(verbose_name="سال"),
        ),
        migrations.DeleteModel(
            name="ProjectDetailModels",
        ),
    ]
