# Generated by Django 4.2 on 2026-07-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_projectmodel_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmodel",
            name="building_area",
        ),
        migrations.RemoveField(
            model_name="projectmodel",
            name="floor_area",
        ),
        migrations.RemoveField(
            model_name="projectmodel",
            name="rooms",
        ),
        migrations.RemoveField(
            model_name="projectmodel",
            name="total_area",
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="architect",
            field=models.CharField(blank=True, max_length=255, verbose_name="معمار"),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="display_date",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="تاریخ نمایشی"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="duration",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="شرایط (مدت زمان)"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="feature_five_desc",
            field=models.TextField(blank=True, verbose_name="ویژگی ۵ - توضیح"),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="feature_five_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ویژگی ۵ - عنوان"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="feature_four_desc",
            field=models.TextField(blank=True, verbose_name="ویژگی ۴ - توضیح"),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="feature_four_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ویژگی ۴ - عنوان"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="feature_one_desc",
            field=models.TextField(blank=True, verbose_name="ویژگی ۱ - توضیح"),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="feature_one_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ویژگی ۱ - عنوان"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="feature_three_desc",
            field=models.TextField(blank=True, verbose_name="ویژگی ۳ - توضیح"),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="feature_three_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ویژگی ۳ - عنوان"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="feature_two_desc",
            field=models.TextField(blank=True, verbose_name="ویژگی ۲ - توضیح"),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="feature_two_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ویژگی ۲ - عنوان"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="stat_four_label",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="آمار ۴ - برچسب"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="stat_four_value",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="آمار ۴ - مقدار"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="stat_one_label",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="آمار ۱ - برچسب"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="stat_one_value",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="آمار ۱ - مقدار"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="stat_three_label",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="آمار ۳ - برچسب"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="stat_three_value",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="آمار ۳ - مقدار"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="stat_two_label",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="آمار ۲ - برچسب"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="stat_two_value",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="آمار ۲ - مقدار"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="strategy",
            field=models.CharField(blank=True, max_length=255, verbose_name="استراتژی"),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="client",
            field=models.CharField(blank=True, max_length=255, verbose_name="مشتری"),
        ),
    ]
