# Generated by Django 4.2 on 2026-07-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_remove_projectmodel_building_area_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectcategorymodel",
            options={
                "verbose_name": "دسته\u200cبندی پروژه",
                "verbose_name_plural": "دسته\u200cبندی های پروژه",
            },
        ),
    ]
