# Generated by Django 4.2 on 2026-07-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_projectcategorymodel_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectmodel",
            old_name="categories",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="projectmodel",
            old_name="extra_categories",
            new_name="extra_category",
        ),
    ]
