# Generated by Django 4.2 on 2026-07-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "برچسب",
                "verbose_name_plural": "برچسب ها",
                "ordering": ["title"],
            },
        ),
        migrations.AlterModelOptions(
            name="categorymodels",
            options={
                "ordering": ["title"],
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
        migrations.AddField(
            model_name="categorymodels",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="productmodels",
            name="sku",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="کد محصول (SKU)",
            ),
        ),
        migrations.AddField(
            model_name="productmodels",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ProductReviewModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 ستاره"),
                            (2, "2 ستاره"),
                            (3, "3 ستاره"),
                            (4, "4 ستاره"),
                            (5, "5 ستاره"),
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop.productmodels",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر محصول",
                "verbose_name_plural": "نظرات محصول",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductImageModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="shop/gallery/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="shop.productmodels",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر گالری محصول",
                "verbose_name_plural": "گالری تصاویر محصول",
            },
        ),
        migrations.AddField(
            model_name="productmodels",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="shop.tagmodels"
            ),
        ),
    ]
