# Generated by Django 4.2 on 2026-07-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_wishlistmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmodels",
            old_name="categories",
            new_name="category",
        ),
    ]
