# Generated by Django 4.2 on 2026-07-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_newslettersubscribermodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=20, verbose_name="سال")),
                ("title", models.CharField(max_length=255, verbose_name="عنوان جایزه")),
                (
                    "category",
                    models.CharField(max_length=255, verbose_name="دسته\u200cبندی"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="image/awards/", verbose_name="تصویر"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نمایش در سایت"),
                ),
            ],
            options={
                "verbose_name": "جایزه",
                "verbose_name_plural": "جوایز و دستاوردها",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HistoryItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="image/history/", verbose_name="تصویر"),
                ),
                ("year", models.CharField(max_length=20, verbose_name="سال")),
                ("description", models.TextField(verbose_name="توضیح")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نمایش در سایت"),
                ),
            ],
            options={
                "verbose_name": "سابقه",
                "verbose_name_plural": "سابقه ما",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProcessStepModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="image/process/", verbose_name="تصویر"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیح")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نمایش در سایت"),
                ),
            ],
            options={
                "verbose_name": "مرحله کاری",
                "verbose_name_plural": "مراحل کاری (معماری استثنایی)",
                "ordering": ["order"],
            },
        ),
    ]
