# Generated by Django 4.2 on 2026-07-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_awardmodel_historyitemmodel_processstepmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessagemodel",
            options={"verbose_name": "پیام", "verbose_name_plural": "پیام ها"},
        ),
        migrations.AlterModelOptions(
            name="newslettersubscribermodel",
            options={"verbose_name": "خبرنامه", "verbose_name_plural": "خبرنامه ها"},
        ),
        migrations.AlterModelOptions(
            name="processstepmodel",
            options={
                "ordering": ["order"],
                "verbose_name": "مرحله کاری",
                "verbose_name_plural": "مراحل کاری",
            },
        ),
    ]
