# Generated by Django 4.2 on 2026-07-22 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0004_alter_contactmessagemodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessagemodel",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="خوانده شده"),
        ),
        migrations.AddField(
            model_name="contactmessagemodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
