# Generated by Django 4.2 on 2026-07-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_contactmessagemodel_is_read_contactmessagemodel_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="awardmodel",
            old_name="categories",
            new_name="category",
        ),
    ]
