# Generated by Django 4.2 on 2026-07-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="image/gallery/", verbose_name="تصویر"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="متن جایگزین",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نمایش در سایت"),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تصویر گالری",
                "verbose_name_plural": "گالری تصاویر",
                "ordering": ["order", "-created_date"],
            },
        ),
    ]
