# Generated by Django 4.2 on 2026-07-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="image/")),
                ("description", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("skill_one", models.CharField(max_length=100)),
                ("skill_one_percent", models.PositiveIntegerField(default=0)),
                ("skill_two", models.CharField(max_length=100)),
                ("skill_two_percent", models.PositiveIntegerField(default=0)),
                ("skill_three", models.CharField(max_length=100)),
                ("skill_three_percent", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "عضو تیم",
                "verbose_name_plural": "اعضای تیم",
                "ordering": ["id"],
            },
        ),
    ]
