# Generated by Django 4.2 on 2026-07-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammodels",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="مدیر شرکت"),
        ),
        migrations.AddField(
            model_name="teammodels",
            name="manager_quote",
            field=models.TextField(blank=True, null=True, verbose_name="متن نظر مدیر"),
        ),
    ]
