# Generated by Django 4.2 on 2026-07-15 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "برچسب",
                "verbose_name_plural": "برچسب ها",
            },
        ),
        migrations.CreateModel(
            name="CommentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=150, verbose_name="نام کامل")),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="وب سایت"),
                ),
                ("message", models.TextField(verbose_name="متن نظر")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="تایید شده"),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blogmodels",
                        verbose_name="مقاله",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرات",
                "ordering": ["-created_date"],
            },
        ),
        migrations.AddField(
            model_name="blogmodels",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="blogs",
                to="blog.tagmodel",
                verbose_name="برچسب ها",
            ),
        ),
    ]
