# Generated by Django 4.2 on 2026-07-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_tagmodel_commentmodel_blogmodels_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogmodels",
            old_name="categories",
            new_name="category",
        ),
    ]
